apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdex-app-dev
  labels:
    app: pdex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdex
  template:
    metadata:
      labels:
        app: pdex
      # annotations:
      #   vault.hashicorp.com/agent-inject: 'true'
      #   vault.hashicorp.com/agent-inject-token: 'true'
      #   vault.hashicorp.com/agent-pre-populate-only: 'true'
      #   vault.hashicorp.com/auth-path: 'auth/k8s-gold'
      #   vault.hashicorp.com/namespace: 'platform-services'
      #   vault.hashicorp.com/role: 'fe0394-nonprod'
      #   vault.hashicorp.com/agent-inject-secret-secrets.env: 'fe0394-nonprod/secrets.env'
      #   vault.hashicorp.com/agent-inject-template-secrets.env: |
      #     {{- with secret "fe0394-nonprod/secrets.env" }}
      #     {{- range $k, $v := .Data.data }}
      #     {{ $k }}={{ $v }}{{ end -}}
      #     {{- end  }}

    spec:
      serviceAccountName: pdex-sa-dev
      containers:
      - name: pdex
        image: 977069300318.dkr.ecr.ca-central-1.amazonaws.com/pdex:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - '-c'
                - >
                  touch /var/www/html/storage/logs/laravel.log && tail -f
                  /var/www/html/storage/logs/laravel.log > /proc/1/fd/2 &
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /var/www/html/probe-check.sh
          initialDelaySeconds: 1000
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdex-sa-dev

---
apiVersion: v1
kind: Service
metadata:
  name: pdex-service-dev
spec:
  selector:
    app: pdex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdex-ingress-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

spec:
  rules:
  - host: dev.pdex.gov.bc.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdex-service-dev
            port:
              number: 80
